---
name: Build and Push docker image to Google Cloud Platform
on:
  push:
    branches: [master]
jobs:
  build-push-gcp:
    name: Build and Push docker image to Google Cloud Platform
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: kanye-bot
      PROJECT_ID: kanye-discord-bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet
      
      - name: Push Docker Image to Artifact Registry
        run: |-
          docker tag ${{ env.IMAGE_NAME }} southamerica-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/${{ env.IMAGE_NAME }}
          docker push southamerica-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/${{ env.IMAGE_NAME }}